# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

defaults: &defaults
  ldap:
    service_dn: 'service_dn'
    service_password: 'password'
    attrs: [ 'givenname', 'sn', 'cn' ]
    airbrake_key: 'airbrake_key'
  refworks:
    ADMIN_USERNAME: 'Username'
    ADMIN_PASSWORD: 'Password'

development:
  <<: *defaults
  secret_key_base: 'key'
  api_token: "token"
  database:
    username: "root"
    database: "factotum_development"
  coral_database:
    username: "root"
    database: "coral_licensing"
    host: "localhost"
  find_text:
    url: "findtext_api_url"
  okta:
    auth_server_id: <server_id>
    client_id: <client_id>
    client_secret: <client_secret>
    domain: okta
    org: nd
    base_auth_url: https://nd.okta.com/oauth2/
    redirect_url: https://localhost:3000/users/auth/oktaoauth/callback

test:
  <<: *defaults
  secret_key_base: "123456789"
  api_token: "xyz"
  database:
    username: "root"
    database: "factotum_test"

# Do not keep production secrets in the repository,
# instead read values from the environment.
pre_production:
  <<: *defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_token:

production:
  <<: *defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_token:
